name: Generate AI Content

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Увеличиваем таймаут
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Generate content
      env:
        HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
      run: |
        python news_generator.py

    - name: Upload generated files
      uses: actions/upload-artifact@v3
      with:
        name: generated-content
        path: |
          article.txt
          tilda_data.json
          article_image_*.jpg

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add article.txt tilda_data.json article_image_*.jpg
        git diff --staged --quiet || (git commit -m "Auto-generated content $(date +'%Y-%m-%d %H:%M')" && git push)
